Fix openstacksdk to 0.29.0 for OSP 16
This workaround avoids this error when installing dependencies when
using source git in OSP 16 virtual environment:

ERROR: No matching distribution found for platformdirs>=3 (from
openstacksdk>=0.29.0->metalsmith->-r /home/stack//plugins/nfv-tempest-
plugin.git/requirements.txt (line 6))
WARNING: You are using pip version 19.3.1; however, version 21.3.1 is
available.
You should consider upgrading via the 'pip install --upgrade pip'
command.

The problem could be solved upgrading pip before installing as it is
said in the error output but currently we have a restriction pip<20
in infrared/common/roles/create_venv/tasks/main.yml (see "Upgrade pip
if it is old" task). In order to apply the openstacksdk>=0.29.0
restriction to OSP 16 (so far this issue does not occur for OSP 17) is
applied only if python_version <= 3.6 because OSP 16 run on
rhel8/python3.6 and OSP 17 run on rhe9/python3.9.

Change-Id: I214e345e1de08b9dda3b927848cb23e2e1f42baa
(cherry picked from commit f2a03721eec1f4aa114703c6dff07912eadbbcab)