Fix issue in qos testcase
Now it is possible to select ports either with vnic type or with
network_id
  File "test_nfv_dpdk_usecases.py", line 247, in test_dpdk_max_qos
    self.run_iperf_test(qos_policies, servers, key_pair,
TypeError: run_iperf_test() got an unexpected keyword argument 'vnic_type'

Change-Id: I60640fdb19902985184eaff8b04014778ef36d0d
(cherry picked from commit c46b5fd7f7248887c3a65ef66fa0261b21ba9838)