[package-freeze]
Current
aggr = self.aggregates_client.create_aggregate(name=aggr_name)
Is broken, since tempest requirements.txt
has the following condition
./openstack-tempest/requirements.txt:jsonschema>=3.2.0 # MIT
jsonschema release the 4.0.0 version
which results:
AttributeError: module 'jsonschema' has no attribute 'compat'